services:
  - type: web
    name: e-report-barangay
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && cd server && npm install && cd ../client && npm install && cd .. && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATA_DIR
        value: /var/data
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1